language: php 

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

notifications:
  email:
    - midoks@163.com
   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./src/travis/compile.sh

# Run PHPs run-tests.php 
script:
    - ./src/travis/run-test.sh
